ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS pda_confirmed  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS liquidity_type TEXT    NULL,
  ADD COLUMN IF NOT EXISTS clean_reaction BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ny_killzone    BOOLEAN NOT NULL DEFAULT FALSE;
